CREATE DATABASE urlShortener;
USE urlShortener;

CREATE TABLE urls (
    id INT AUTO_INCREMENT PRIMARY KEY,
    shortId VARCHAR(10) UNIQUE NOT NULL,
    longUrl TEXT NOT NULL,
    visits INT DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



SELECT * FROM urls;

SELECT * FROM urls WHERE shortId = 'qW5CNcRM';
